version: "1"
rules:
  - base: master
    upstream: guerrillacontra:master    # change `wei` to the owner of upstream repo
    mergeMethod: hardreset
 # create pull request when local master is updated
  - base: upm-convert
    upstream: master